version: "3.7"

services:

  server:
    image: benderbendingrodriges/admin-server:latest
    restart: on-failure
    ports:
      - 9003:9003

  client:
    image: benderbendingrodriges/dockertaskrepo:latest
    restart: on-failure
    depends_on:
      - server
    ports:
      - 8080:8080